services:
  mysql:
    image: mysql:8.0
    container_name: farmtech-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FarmTech
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: farmtech-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/FarmTech
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080
      ML_SERVICE_BASE: http://ml-service:5001
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./farmer-rental-app
      args:
        REACT_APP_API_BASE_URL: /api
    container_name: farmtech-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  ml-service:
    build:
      context: ./ml-service
    container_name: farmtech-ml
    ports:
      - "5001:5001"

volumes:
  db_data:
